post http://localhost:5050/user/signup
Content-Type: application/json

{
    "username" : "Uday_116",
    "email" : "uday@gmail.com",
    "password" : "uday"
}

###
post http://localhost:5050/user/login
Content-Type: application/json

{
    "username" : "Uday_116",
    "password" : "uday"
}

###
get http://localhost:5050/user/logout